version: '2'
services:

  paladin-server:
    image: gizmo-gg/paladin
    build: paladin
    ports:
      - 8080
    depends_on:
      - postgres
    environment:
      - PALADIN_DATABASE=host=postgres user=postgres
      - PALADIN_WORKER=False
    volumes:
      - paladin-data:/project/data

  paladin-worker:
    image: gizmo-gg/paladin
    build: paladin
    depends_on:
      - postgres
    environment:
      - PALADIN_DATABASE=host=postgres user=postgres
      - PALADIN_SERVER=False
    volumes:
      - paladin-data:/project/data

  merc:
    image: gizmo-gg/merc
    build: merc
    ports:
      - 8081

  postgres:
    image: postgres:9.6
    ports:
      - 5432

  venom:
    image: gizmo-gg/venom
    build: venom
    ports:
      - 8080:80
    depends_on:
      - paladin-server
      - merc

volumes:
  paladin-data: null
