version: '2'
services:

  jalopy:
    image: gizmo-gg/jalopy
    build: jalopy
    ports:
      - 8080
    depends_on:
      - postgres
    environment:
      - JALOPY_DATABASE=host=postgres user=postgres

  merc:
    image: gizmo-gg/merc
    build: merc
    ports:
      - 8081

  postgres:
    image: postgres:9.6
    ports:
      - 5432

  nginx:
    image: gizmo-gg/nginx
    build: .
    ports:
      - 8080:80
    depends_on:
      - jalopy
      - merc
