version: '2.1'
services:

  takumi:
    image: gizmo-gg/takumi
    build: takumi
    ports:
      - 8080
    depends_on:
      - postgres
    environment:
      TAKUMI_DATABASE: postgres://postgres@postgres:5432/postgres
      TAKUMI_URL: ${TAKUMI_URL:-http://localhost:8080/takumi}
    volumes:
      - paladin-data:/project/data

  paladin-server:
    image: gizmo-gg/paladin
    build: paladin
    ports:
      - 8080
    depends_on:
      - postgres
    environment:
      # This must be set at run time to the URL that the API is available at.
      # For local development, Paladin is proxied behind Venom. In production,
      # that's also true, but the entire site is at `gizmo.gg` instead of
      # `localhost:8080`. Don't include a trailing slash in this URL!
      - PALADIN_CONNECT=${PALADIN_CONNECT:-http://localhost:8080/api}
      - PALADIN_DATABASE=host=postgres user=postgres
      - PALADIN_WORKER=False
    volumes:
      - paladin-data:/project/data

  paladin-worker:
    image: gizmo-gg/paladin
    build: paladin
    depends_on:
      - paladin-server
      - postgres
    environment:
      - PALADIN_DATABASE=host=postgres user=postgres
      - PALADIN_MIGRATE=False
      - PALADIN_SERVER=False
    volumes:
      - paladin-data:/project/data

  merc:
    image: gizmo-gg/merc
    build:
      context: merc
      args:
        # This must be set at build time to the URL that the API will be
        # availabe at. In that way it's similar to the `PALADIN_CONNECT`
        # variable. This one (a) needs a trailing slash and (b) must be a valid
        # JavaScript expression. That means wrapping it in quotes.
        API_URL: '${MERC_API_URL:-"http://localhost:8080/api/"}'
    ports:
      - 8081
    depends_on:
      - paladin-server
      - takumi

  postgres:
    image: postgres:9.6
    ports:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  venom:
    image: gizmo-gg/venom
    build: venom
    ports:
      - 8080:80
    depends_on:
      - paladin-server
      - merc
      - takumi

volumes:
  paladin-data: null
  postgres-data: null
