CREATE TABLE games_players (
  id serial PRIMARY KEY,
  game_id integer NOT NULL REFERENCES games (id),
  player_id integer NOT NULL REFERENCES players (id),
  name character varying(100) NOT NULL,
  xp integer NOT NULL,
  is_blue boolean NOT NULL,
  is_present_at_end boolean NOT NULL,
  score integer NOT NULL,
  goals integer NOT NULL,
  assists integer NOT NULL,
  saves integer NOT NULL,
  shots integer NOT NULL,
  body_id integer NOT NULL REFERENCES bodies (id),
  decal_id integer NOT NULL REFERENCES decals (id),
  wheel_id integer NOT NULL REFERENCES wheels (id),
  rocket_trail_id integer NOT NULL REFERENCES rocket_trails (id),
  antenna_id integer NOT NULL REFERENCES antennas (id),
  topper_id integer NOT NULL REFERENCES toppers (id),
  wheel_paint_id integer REFERENCES paints (id),
  topper_paint_id integer REFERENCES paints (id),
  primary_color_id integer NOT NULL REFERENCES colors (id),
  accent_color_id integer NOT NULL REFERENCES colors (id),
  primary_finish_id integer NOT NULL REFERENCES finishes (id),
  accent_finish_id integer NOT NULL REFERENCES finishes (id),
  fov real NOT NULL,
  height real NOT NULL,
  angle real NOT NULL,
  distance real NOT NULL,
  stiffness real NOT NULL,
  swivel_speed real NOT NULL,
  UNIQUE (game_id, player_id)
)
