name: paladin
version: '1.0.0'
synopsis: Analyze Rocket League replays.
description: Paladin analyzes Rocket League replays.

executables:
  paladin:
    source-dirs: source/executable
    main: Main.hs
    dependencies:
      - base
      - paladin
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

library:
  source-dirs: source/library
  dependencies:
    - aeson
    - aeson-casing
    - base
    - bytestring
    - containers
    - cryptonite
    - directory
    - envy
    - filepath
    - http-types
    - postgresql-simple
    - postgresql-simple-migration
    - rattletrap
    - text
    - time
    - uuid
    - wai
    - wai-extra
    - warp

tests:
  test:
    source-dirs: source/test
    main: Main.hs
    dependencies:
      - aeson
      - base
      - bytestring
      - paladin
      - wai
      - wai-extra
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

category: Game, Web
extra-source-files:
  - migrations/*.sql
ghc-options:
  - -Wall
license: AllRightsReserved
maintainer: Taylor Fausak
